### ISSUE TITLE
Plotting data from an invalid time

### ISSUE THREAD

**Issue by diegotorres1** [zotbins/ZotBins_RaspPi#1]
Data is being plotted even though the time is invalid. This is true for weight, divergence, and fullness.

start time : 2019-05-02 04:12 PM
end time : 2019-05-02 04:13 PM

Used Microsoft Edge browser.

![error](https://user-images.githubusercontent.com/35505775/57170135-99524e80-6dbf-11e9-9fcc-fff1be1acafa.PNG)

**Comment by okyang** [comment]
This is a web issue
